title: This Bunch are Brilliant
author: Brillant-Matt
email: mmcguire@brilliant.com
description: Practical capital put to work by brilliant entrepeneurs.

remote_theme: brilliant-mmcguire/jekyll-serif-theme
baseurl: /brilliant-mmcguire/jekyll-serif-theme
