title: Brilliant Bunch 
description: Uniting time, energy, know-how and money to build a sustainable, prosperous and fair society.

author: brillant-mmcguire
email: mmcguire@brilliantbunch.net
description: > # this means to ignore newlines until "baseurl:"
  Practical capital put to work by brilliant entrepeneurs.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

#theme: minima
theme: jekyll-theme-leap-day
